### ISSUE TITLE
这是在学习嘛

### ISSUE THREAD

**Issue by tybkyk** [kyao233/spring_boot#25]

**Comment by kyao233** [comment]
你猜。

**Comment by tybkyk** [comment]
哈哈哈，有空可以交流下

**Comment by kyao233** [comment]
![avatar](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1575097523445&di=018fb8344576fef1d53fccb2bdc2b5b2&imgtype=0&src=http%3A%2F%2Fhbimg.b0.upaiyun.com%2F2c2400b153090e6136112f63bf0e150672a64fd63dc0-HQHYpL_fw658)

**Comment by kyao233** [comment]
有空可以让你看看我的绝活小小。

**Comment by tybkyk** [comment]
意思现在dota2玩的风生水起
